In [2]:
import sys
sys.executable

'c:\\Users\\anshuman\\Desktop\\toxic-comment-detection\\venv\\Scripts\\python.exe'

In [3]:
import pandas as pd 
import os

In [4]:
df = pd.read_csv("train.csv")
df.head()

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0

In [5]:
text_column = "comment_text"
label_columns = ["toxic", "severe_toxic", "obscene", "threat","insult", "identity_hate"]

df[text_column].head()

0    Explanation\nWhy the edits made under my usern...
1    D'aww! He matches this background colour I'm s...
2    Hey man, I'm really not trying to edit war. It...
3    "\nMore\nI can't make any real suggestions on ...
4    You, sir, are my hero. Any chance you remember...
Name: comment_text, dtype: object

In [6]:
df.shape

(159571, 8)

In [7]:
df[label_columns].sum().sort_values(ascending=False)

toxic            15294
obscene           8449
insult            7877
severe_toxic      1595
identity_hate     1405
threat             478
dtype: int64

In [8]:
df["clean"] = (df[label_columns].sum(axis=1)==0)
df["clean"].value_counts()

clean
True     143346
False     16225
Name: count, dtype: int64

In [9]:
df[label_columns].sum(axis=1).value_counts().head()

0    143346
1      6360
3      4209
2      3480
4      1760
Name: count, dtype: int64

# Baseline model

In [10]:
X = df["comment_text"]
Y = df[label_columns]

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y,
    test_size=0.2,
    random_state=42
)

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=20000,
    ngram_range=(1,2)
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier

model = OneVsRestClassifier(
    LogisticRegression(max_iter=1000)
)

model.fit(X_train_tfidf,Y_train)

OneVsRestClassifier(estimator=LogisticRegression(max_iter=1000))

In [14]:
y_pred = model.predict(X_test_tfidf)

In [15]:
from sklearn.metrics import classification_report

print(classification_report(Y_test, y_pred, target_names=label_columns))

               precision    recall  f1-score   support

        toxic       0.92      0.61      0.73      3056
 severe_toxic       0.59      0.21      0.30       321
      obscene       0.92      0.60      0.72      1715
       threat       0.47      0.09      0.16        74
       insult       0.85      0.51      0.64      1614
identity_hate       0.75      0.15      0.25       294

    micro avg       0.89      0.54      0.67      7074
    macro avg       0.75      0.36      0.47      7074
 weighted avg       0.88      0.54      0.66      7074
  samples avg       0.06      0.05      0.05      7074

c:\Users\anshuman\Desktop\toxic-comment-detection\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\anshuman\Desktop\toxic-comment-detection\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\anshuman\Desktop\toxic-comment-detection\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in samples with no true nor predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

here normal logistic regression and TF-IDF (baseline model) fails due to small represtation of some label in dataset and not considerring the context of word used. thus we use BERT so model can take decision based on the context of the comment also.

In [16]:
import pandas as pd
import numpy as np
import torch

from transformers import DistilBertTokenizerFast, DistilBertForSequenceClassification

from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, accuracy_score

c:\Users\anshuman\Desktop\toxic-comment-detection\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
W0513 14:25:06.349000 3520 Lib\site-packages\torch\distributed\elastic\multiprocessing\redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.

In [17]:
df = pd.read_csv("train.csv")

df.head()

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0

In [18]:
labels = df.columns[2:]

df['labels'] = df[labels].values.tolist()

In [19]:
train_df, val_df = train_test_split(df, test_size=0.1, random_state=42)

In [20]:
tokenizer = DistilBertTokenizerFast.from_pretrained('distilbert-base-uncased')

c:\Users\anshuman\Desktop\toxic-comment-detection\venv\Lib\site-packages\huggingface_hub\file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

In [21]:
train_encodings = tokenizer(
    train_df["comment_text"].tolist(),
    truncation=True,
    padding=True,
    max_length=128
)

val_encodings = tokenizer(
    val_df["comment_text"].tolist(),
    truncation=True,
    padding=True,
    max_length=128
)

In [22]:
class ToxicDataset(torch.utils.data.Dataset):

    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):

        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx]).float()

        return item

    def __len__(self):
        return len(self.labels)

In [23]:
train_dataset = ToxicDataset(train_encodings, train_df["labels"].tolist())
val_dataset = ToxicDataset(val_encodings, val_df["labels"].tolist())

In [24]:
print(len(train_dataset))
print(len(val_dataset))

143613
15958

In [25]:
from torch.utils.data import Subset

In [26]:
train_dataset = Subset(train_dataset, range(20000))
val_dataset = Subset(val_dataset, range(5000))

In [27]:
model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=6,
    problem_type="multi_label_classification"
)

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [28]:
import sys
print(sys.executable)

c:\Users\anshuman\Desktop\toxic-comment-detection\venv\Scripts\python.exe

In [29]:
!pip install accelerate

Requirement already satisfied: accelerate in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (0.27.2)
Requirement already satisfied: numpy>=1.17 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from accelerate) (2.4.0)
Requirement already satisfied: packaging>=20.0 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from accelerate) (25.0)
Requirement already satisfied: psutil in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from accelerate) (7.2.1)
Requirement already satisfied: pyyaml in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from accelerate) (6.0.3)
Requirement already satisfied: torch>=1.10.0 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from accelerate) (2.9.1)
Requirement already satisfied: huggingface-hub in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from accelerate) (0.36.0)
Requirement already satisfied: safetensors>=0.3.1 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from accelerate) (0.7.0)
Requirement already satisfied: filelock in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from torch>=1.10.0->accelerate) (3.20.2)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from torch>=1.10.0->accelerate) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from torch>=1.10.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from torch>=1.10.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from torch>=1.10.0->accelerate) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from torch>=1.10.0->accelerate) (2025.12.0)
Requirement already satisfied: requests in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from huggingface-hub->accelerate) (2.32.5)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from huggingface-hub->accelerate) (4.67.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from sympy>=1.13.3->torch>=1.10.0->accelerate) (1.3.0)
Requirement already satisfied: colorama in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from tqdm>=4.42.1->huggingface-hub->accelerate) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from jinja2->torch>=1.10.0->accelerate) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from requests->huggingface-hub->accelerate) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from requests->huggingface-hub->accelerate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from requests->huggingface-hub->accelerate) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from requests->huggingface-hub->accelerate) (2025.11.12)

[notice] A new release of pip available: 22.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [30]:
import accelerate
print(accelerate.__version__)

0.27.2

In [31]:
import accelerate
import transformers
import torch

print("Accelerate:", accelerate.__version__)
print("Transformers:", transformers.__version__)
print("Torch:", torch.__version__)

Accelerate: 0.27.2
Transformers: 4.38.2
Torch: 2.9.1+cpu

In [32]:
from transformers import TrainingArguments

In [33]:
training_args = TrainingArguments(
    output_dir="./results",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=1,
    weight_decay=0.01,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    logging_steps=100
)

In [34]:
from transformers import DistilBertForSequenceClassification

model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=6
)

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [35]:
print(type(train_dataset))

print("df" in globals())
print("train_dataset" in globals())
print("val_dataset" in globals())
print("model" in globals())

<class 'torch.utils.data.dataset.Subset'>
True
True
True
True

In [36]:
!pip install transformers==4.38.2
!pip install accelerate==0.27.2

Requirement already satisfied: transformers==4.38.2 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (4.38.2)
Requirement already satisfied: filelock in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from transformers==4.38.2) (3.20.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from transformers==4.38.2) (0.36.0)
Requirement already satisfied: numpy>=1.17 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from transformers==4.38.2) (2.4.0)
Requirement already satisfied: packaging>=20.0 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from transformers==4.38.2) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from transformers==4.38.2) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from transformers==4.38.2) (2025.11.3)
Requirement already satisfied: requests in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from transformers==4.38.2) (2.32.5)
Requirement already satisfied: tokenizers<0.19,>=0.14 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from transformers==4.38.2) (0.15.2)
Requirement already satisfied: safetensors>=0.4.1 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from transformers==4.38.2) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from transformers==4.38.2) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.38.2) (2025.12.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.38.2) (4.15.0)
Requirement already satisfied: colorama in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from tqdm>=4.27->transformers==4.38.2) (0.4.6)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from requests->transformers==4.38.2) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from requests->transformers==4.38.2) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from requests->transformers==4.38.2) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from requests->transformers==4.38.2) (2025.11.12)

[notice] A new release of pip available: 22.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: accelerate==0.27.2 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (0.27.2)
Requirement already satisfied: numpy>=1.17 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from accelerate==0.27.2) (2.4.0)
Requirement already satisfied: packaging>=20.0 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from accelerate==0.27.2) (25.0)
Requirement already satisfied: psutil in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from accelerate==0.27.2) (7.2.1)
Requirement already satisfied: pyyaml in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from accelerate==0.27.2) (6.0.3)
Requirement already satisfied: torch>=1.10.0 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from accelerate==0.27.2) (2.9.1)
Requirement already satisfied: huggingface-hub in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from accelerate==0.27.2) (0.36.0)
Requirement already satisfied: safetensors>=0.3.1 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from accelerate==0.27.2) (0.7.0)
Requirement already satisfied: filelock in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from torch>=1.10.0->accelerate==0.27.2) (3.20.2)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from torch>=1.10.0->accelerate==0.27.2) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from torch>=1.10.0->accelerate==0.27.2) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from torch>=1.10.0->accelerate==0.27.2) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from torch>=1.10.0->accelerate==0.27.2) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from torch>=1.10.0->accelerate==0.27.2) (2025.12.0)
Requirement already satisfied: requests in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from huggingface-hub->accelerate==0.27.2) (2.32.5)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from huggingface-hub->accelerate==0.27.2) (4.67.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from sympy>=1.13.3->torch>=1.10.0->accelerate==0.27.2) (1.3.0)
Requirement already satisfied: colorama in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from tqdm>=4.42.1->huggingface-hub->accelerate==0.27.2) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from jinja2->torch>=1.10.0->accelerate==0.27.2) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from requests->huggingface-hub->accelerate==0.27.2) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from requests->huggingface-hub->accelerate==0.27.2) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from requests->huggingface-hub->accelerate==0.27.2) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\anshuman\desktop\toxic-comment-detection\venv\lib\site-packages (from requests->huggingface-hub->accelerate==0.27.2) (2025.11.12)

[notice] A new release of pip available: 22.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [37]:
from transformers import Trainer

In [38]:
trainer = Trainer(

    model=model,

    args=training_args,

    train_dataset=train_dataset,

    eval_dataset=val_dataset
)

In [41]:
print(len(train_dataset))
print(len(val_dataset))

20000
5000

In [43]:
print(training_args.num_train_epochs)

1

In [45]:
trainer.train()

  2%|▏         | 46/2500 [02:44<2:25:51,  3.57s/it]
  4%|▍         | 100/2500 [03:22<1:45:07,  2.63s/it]

{'loss': 0.1152, 'grad_norm': 0.41188153624534607, 'learning_rate': 1.9200000000000003e-05, 'epoch': 0.04}

  8%|▊         | 200/2500 [06:36<1:07:46,  1.77s/it]

{'loss': 0.0685, 'grad_norm': 0.8222015500068665, 'learning_rate': 1.8400000000000003e-05, 'epoch': 0.08}

 12%|█▏        | 300/2500 [09:30<1:05:25,  1.78s/it]

{'loss': 0.0747, 'grad_norm': 0.5549344420433044, 'learning_rate': 1.76e-05, 'epoch': 0.12}

 16%|█▌        | 400/2500 [12:35<1:04:08,  1.83s/it]

{'loss': 0.0734, 'grad_norm': 1.2068936824798584, 'learning_rate': 1.6800000000000002e-05, 'epoch': 0.16}

 20%|██        | 500/2500 [15:29<55:13,  1.66s/it]

{'loss': 0.0512, 'grad_norm': 2.7292137145996094, 'learning_rate': 1.6000000000000003e-05, 'epoch': 0.2}

 24%|██▍       | 600/2500 [18:25<55:47,  1.76s/it]

{'loss': 0.064, 'grad_norm': 3.969568967819214, 'learning_rate': 1.5200000000000002e-05, 'epoch': 0.24}

 28%|██▊       | 700/2500 [21:23<1:02:42,  2.09s/it]

{'loss': 0.0627, 'grad_norm': 2.635340690612793, 'learning_rate': 1.4400000000000001e-05, 'epoch': 0.28}

 32%|███▏      | 800/2500 [24:29<48:05,  1.70s/it]

{'loss': 0.0528, 'grad_norm': 0.06550406664609909, 'learning_rate': 1.3600000000000002e-05, 'epoch': 0.32}

 36%|███▌      | 900/2500 [27:28<46:01,  1.73s/it]

{'loss': 0.0657, 'grad_norm': 5.182737827301025, 'learning_rate': 1.2800000000000001e-05, 'epoch': 0.36}

 40%|████      | 1000/2500 [30:21<43:41,  1.75s/it]

{'loss': 0.0461, 'grad_norm': 0.04331379756331444, 'learning_rate': 1.2e-05, 'epoch': 0.4}

 44%|████▍     | 1100/2500 [33:14<40:22,  1.73s/it]

{'loss': 0.0543, 'grad_norm': 0.04103900119662285, 'learning_rate': 1.1200000000000001e-05, 'epoch': 0.44}

 48%|████▊     | 1200/2500 [36:13<49:21,  2.28s/it]

{'loss': 0.0601, 'grad_norm': 0.15506812930107117, 'learning_rate': 1.04e-05, 'epoch': 0.48}

 52%|█████▏    | 1300/2500 [39:15<33:02,  1.65s/it]

{'loss': 0.0583, 'grad_norm': 0.9305071234703064, 'learning_rate': 9.600000000000001e-06, 'epoch': 0.52}

 56%|█████▌    | 1400/2500 [42:08<30:56,  1.69s/it]

{'loss': 0.0434, 'grad_norm': 0.03326871991157532, 'learning_rate': 8.8e-06, 'epoch': 0.56}

 60%|██████    | 1500/2500 [45:00<28:47,  1.73s/it]

{'loss': 0.0314, 'grad_norm': 0.029402200132608414, 'learning_rate': 8.000000000000001e-06, 'epoch': 0.6}

 64%|██████▍   | 1600/2500 [48:04<36:29,  2.43s/it]

{'loss': 0.0527, 'grad_norm': 0.2933541238307953, 'learning_rate': 7.2000000000000005e-06, 'epoch': 0.64}

 68%|██████▊   | 1700/2500 [51:19<22:48,  1.71s/it]

{'loss': 0.0522, 'grad_norm': 0.9012874364852905, 'learning_rate': 6.4000000000000006e-06, 'epoch': 0.68}

 72%|███████▏  | 1800/2500 [54:20<20:03,  1.72s/it]

{'loss': 0.0541, 'grad_norm': 1.05543851852417, 'learning_rate': 5.600000000000001e-06, 'epoch': 0.72}

 76%|███████▌  | 1900/2500 [57:11<16:35,  1.66s/it]

{'loss': 0.0461, 'grad_norm': 0.17283083498477936, 'learning_rate': 4.800000000000001e-06, 'epoch': 0.76}

 80%|████████  | 2000/2500 [59:59<14:30,  1.74s/it]

{'loss': 0.0548, 'grad_norm': 2.422646999359131, 'learning_rate': 4.000000000000001e-06, 'epoch': 0.8}

 84%|████████▍ | 2100/2500 [1:02:47<10:45,  1.61s/it]

{'loss': 0.0493, 'grad_norm': 0.7387848496437073, 'learning_rate': 3.2000000000000003e-06, 'epoch': 0.84}

 88%|████████▊ | 2200/2500 [1:05:26<07:53,  1.58s/it]

{'loss': 0.0521, 'grad_norm': 0.610477864742279, 'learning_rate': 2.4000000000000003e-06, 'epoch': 0.88}

 92%|█████████▏| 2300/2500 [1:08:04<05:18,  1.59s/it]

{'loss': 0.0545, 'grad_norm': 1.7168219089508057, 'learning_rate': 1.6000000000000001e-06, 'epoch': 0.92}

 96%|█████████▌| 2400/2500 [1:10:44<02:38,  1.59s/it]

{'loss': 0.0544, 'grad_norm': 1.274868130683899, 'learning_rate': 8.000000000000001e-07, 'epoch': 0.96}

100%|██████████| 2500/2500 [1:13:23<00:00,  1.57s/it]

{'loss': 0.0527, 'grad_norm': 0.034061331301927567, 'learning_rate': 0.0, 'epoch': 1.0}

100%|██████████| 2500/2500 [1:17:23<00:00,  1.57s/it]Checkpoint destination directory ./results\checkpoint-2500 already exists and is non-empty. Saving will proceed but saved results may be invalid.

{'eval_loss': 0.04354006424546242, 'eval_runtime': 239.7274, 'eval_samples_per_second': 20.857, 'eval_steps_per_second': 2.607, 'epoch': 1.0}

100%|██████████| 2500/2500 [1:17:24<00:00,  1.86s/it]

{'train_runtime': 4644.6814, 'train_samples_per_second': 4.306, 'train_steps_per_second': 0.538, 'train_loss': 0.05778704891204834, 'epoch': 1.0}

TrainOutput(global_step=2500, training_loss=0.05778704891204834, metrics={'train_runtime': 4644.6814, 'train_samples_per_second': 4.306, 'train_steps_per_second': 0.538, 'train_loss': 0.05778704891204834, 'epoch': 1.0})

In [46]:
predictions = trainer.predict(val_dataset)

c:\Users\anshuman\Desktop\toxic-comment-detection\venv\Lib\site-packages\torch\utils\data\dataloader.py:668: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
100%|██████████| 625/625 [04:15<00:00,  2.45it/s]

In [47]:
import torch

logits = predictions.predictions
probs = torch.sigmoid(torch.tensor(logits))

In [48]:
y_pred = (probs > 0.5).int().numpy()

In [49]:
y_true = val_df[labels].values

In [51]:
preds = trainer.predict(val_dataset)

100%|██████████| 625/625 [03:53<00:00,  2.67it/s]

In [52]:
y_pred = preds.predictions
y_true = preds.label_ids

In [53]:
from scipy.special import expit
import numpy as np

y_pred = expit(y_pred)
y_pred = (y_pred > 0.5).astype(int)

In [54]:
from sklearn.metrics import f1_score

f1_micro = f1_score(y_true, y_pred, average="micro")
f1_macro = f1_score(y_true, y_pred, average="macro")

print("Micro F1:", f1_micro)
print("Macro F1:", f1_macro)

Micro F1: 0.751008064516129
Macro F1: 0.39950426778793185

In [55]:
trainer.save_model("toxic_model")
tokenizer.save_pretrained("toxic_model")

('toxic_model\\tokenizer_config.json',
 'toxic_model\\special_tokens_map.json',
 'toxic_model\\vocab.txt',
 'toxic_model\\added_tokens.json',
 'toxic_model\\tokenizer.json')

In [56]:
import torch
from scipy.special import expit

labels = [
    "toxic",
    "severe_toxic",
    "obscene",
    "threat",
    "insult",
    "identity_hate"
]

def predict_toxicity(text):
    
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True
    )

    with torch.no_grad():
        outputs = model(**inputs)

    probs = expit(outputs.logits.numpy())[0]

    predictions = (probs > 0.5).astype(int)

    for label, pred in zip(labels, predictions):
        print(f"{label}: {pred}")

In [57]:
predict_toxicity("You are an idiot and I hate you")

toxic: 1
severe_toxic: 0
obscene: 1
threat: 0
insult: 1
identity_hate: 0

In [58]:
predict_toxicity("You are stupid")
predict_toxicity("I will kill you")
predict_toxicity("Have a nice day")

toxic: 1
severe_toxic: 0
obscene: 1
threat: 0
insult: 1
identity_hate: 0
toxic: 1
severe_toxic: 0
obscene: 1
threat: 0
insult: 1
identity_hate: 0
toxic: 0
severe_toxic: 0
obscene: 0
threat: 0
insult: 0
identity_hate: 0